// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTBLq0kAyPY42_lhT0RCWF_IEKj3VMF4A',
    appId: '1:424315029386:web:16f2b23a5b6410de9baa73',
    messagingSenderId: '424315029386',
    projectId: 'book-recommendation-ce8cc',
    authDomain: 'book-recommendation-ce8cc.firebaseapp.com',
    databaseURL:
        'https://book-recommendation-ce8cc-default-rtdb.firebaseio.com',
    storageBucket: 'book-recommendation-ce8cc.firebasestorage.app',
    measurementId: 'G-93LRWKQC16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD11QROeIYIMNIxWFnRgY1zzjNsnzrOzhU',
    appId: '1:424315029386:android:02d5bc2a103f699c9baa73',
    messagingSenderId: '424315029386',
    projectId: 'book-recommendation-ce8cc',
    databaseURL:
        'https://book-recommendation-ce8cc-default-rtdb.firebaseio.com',
    storageBucket: 'book-recommendation-ce8cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KV1CZ8yIt96YYWCI2DiE6KvtIvTJTlE',
    appId: '1:424315029386:ios:e1bca5b16c03e2b39baa73',
    messagingSenderId: '424315029386',
    projectId: 'book-recommendation-ce8cc',
    databaseURL:
        'https://book-recommendation-ce8cc-default-rtdb.firebaseio.com',
    storageBucket: 'book-recommendation-ce8cc.firebasestorage.app',
    iosBundleId: 'com.example.bookFusionMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KV1CZ8yIt96YYWCI2DiE6KvtIvTJTlE',
    appId: '1:424315029386:ios:e1bca5b16c03e2b39baa73',
    messagingSenderId: '424315029386',
    projectId: 'book-recommendation-ce8cc',
    databaseURL:
        'https://book-recommendation-ce8cc-default-rtdb.firebaseio.com',
    storageBucket: 'book-recommendation-ce8cc.firebasestorage.app',
    iosBundleId: 'com.example.bookFusionMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTBLq0kAyPY42_lhT0RCWF_IEKj3VMF4A',
    appId: '1:424315029386:web:6e64d9148642a7859baa73',
    messagingSenderId: '424315029386',
    projectId: 'book-recommendation-ce8cc',
    authDomain: 'book-recommendation-ce8cc.firebaseapp.com',
    databaseURL:
        'https://book-recommendation-ce8cc-default-rtdb.firebaseio.com',
    storageBucket: 'book-recommendation-ce8cc.firebasestorage.app',
    measurementId: 'G-43PDPXK062',
  );
}
